### PR TITLE
Feature/159/hash to confirm completion

### PR DESCRIPTION
**Pull request by mamcisaac**
Hash Generation feature added (#159)

Before the "Congratulations" page, there is now a "Submit" page that generates a hash that can be submitted.

As per the discussion in #159, I modified the encoder_ui to require students to enter a name and ID. This name and ID are then encoded in the hash (as an "identifier" type), so that submitted names and IDs could theoretically be used to track tutorial completion.

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
@rundel Would you take a look at this implementation and see if this is something that can be done in learnrhash or adding the Shiny logic here makes sense.

Either way let's swap the order of congratulations and hash generation so it's not confusing to students who don't need to submit anything.

**Comment by rundel** [comment]
Something is funky with the diffs were the newlines are not rendering correctly for me making it hard to read the code to see what exactly is happening (I just see a bunch of `^M`s)

It also seems like it is the same code across all of the Rmds, I would strongly recommend making a script file that contains the implementation that is then sourced or read in by the chunks.

**Comment by mine-cetinkaya-rundel** [comment]
That's a good point @rundel, agreed on avoiding redundancy.

I'm wondering if some of this can/should go directly into the learnrhash functions (or versions of them) instead of being defined in the tutorials. Here is a version of that code with line breaks:

````md
## Submit

```{r encoder_ui, echo=FALSE}
hash_encoder_ui <- {
  shiny::div("If you have completed this tutorial and are happy with all of your", "solutions, please enter your identifying information, then click the button below to generate your hash", textInput("name", "What's your name?"), textInput("studentID", "What is your student ID?"), renderText({
    input$caption
  }), )
}
```

```{r encoder_logic, echo=FALSE, context="server"}
is_server_context <- function(.envir) {
  # We are in the server context if there are the follow:
  # * input - input reactive values
  # * output - shiny output
  # * session - shiny session
  #
  # Check context by examining the class of each of these.
  # If any is missing then it will be a NULL which will fail.

  inherits(.envir$input, "reactivevalues") &
    inherits(.envir$output, "shinyoutput") &
    inherits(.envir$session, "ShinySession")
}

check_server_context <- function(.envir) {
  if (!is_server_context(.envir)) {
    calling_func <- deparse(sys.calls()[[sys.nframe() - 1]])
    err <- paste0("Function `", calling_func, "`", " must be called from an Rmd chunk where `context = \"server\"`")
    stop(err, call. = FALSE)
  }
}
encoder_logic <- function(strip_output = FALSE) {
  p <- parent.frame()
  check_server_context(p)
  # Make this var available within the local context below
  assign("strip_output", strip_output, envir = p)
  # Evaluate in parent frame to get input, output, and session
  local(
    {
      encoded_txt <- shiny::eventReactive(
        input$hash_generate,
        {
          # shiny::getDefaultReactiveDomain()$userData$tutorial_state
          state <- learnr:::get_tutorial_state()
          shiny::validate(shiny::need(length(state) > 0, "No progress yet."))
          shiny::validate(shiny::need(nchar(input$name) > 0, "No name entered."))
          shiny::validate(shiny::need(nchar(input$studentID) > 0, "Please enter your student ID"))
          user_state <- purrr::map_dfr(state, identity, .id = "label")
          user_state <- dplyr::group_by(user_state, label, type, correct)
          user_state <- dplyr::summarize(
            user_state,
            answer = list(answer),
            timestamp = dplyr::first(timestamp),
            .groups = "drop"
          )
          user_state <- dplyr::relocate(user_state, correct, .before = timestamp)
          user_info <- tibble(
            label = c("student_name", "student_id"),
            type = "identifier",
            answer = as.list(c(input$name, input$studentID)),
            timestamp = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z", tz = "UTC")
          )
          learnrhash::encode_obj(bind_rows(user_info, user_state))
        }
      )
      output$hash_output <- shiny::renderText(encoded_txt())
    },
    envir = p
  )
}
encoder_logic()
```

```{r encode, echo=FALSE}
learnrhash::encoder_ui(ui_before = hash_encoder_ui)
```

````

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel I added the script files and built a draft for tutorial 1 lesson 1.

**Comment by mamcisaac** [comment]
This is a much more elegant solution. I will update the other files as per @npaterno's draft for tutorial 1 lesson 1. I would love for this to be implemented in time for the upcoming semester!

**Review by mine-cetinkaya-rundel — APPROVED** [review]
Thank you @npaterno and @mamcisaac!

This looks great. One update I'd recommend is moving the `.R` files (including the `deploy.R` file) into a folder called `R` and then sourcing them properly from there.

Also, @npaterno -- when we put these tutorials in a package we'll want to save those functions in the R folder of the package and can just use them in the tutorials

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel I'll make those changes and merge the pr.

**Pull request merged**
